version: '3.9'

services:
  flask_app:
    container_name: Flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:6000/mydatabase
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: Postgres
    ports:
      - "6000:6000"
    expose:
      - "6000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: budgetapp
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 6000

volumes:
  postgres_data:
